import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { backoffDelay, CAPABILITIES, resolvePublicAgentId, validateBrainCloudOrigin } from '../agent/src/runtime.ts';
import { parseAgentMetadata } from '../lib/brain-agent/contracts.ts';
const root=process.cwd(); const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const sql=read('supabase/migration_audit/pre_baseline_20260724/202607220016_brain_agent_secure_pairing.sql');const auditRepairSql=read('supabase/migration_audit/pre_baseline_20260724/202607220017_fix_brain_agent_unknown_capability_audit_conflict.sql');const identifierRepairSql=read('supabase/migration_audit/pre_baseline_20260724/202607220018_fix_brain_agent_rpc_identifier_ambiguity.sql');
const coreCapabilitySql=read('supabase/migrations/202607240004_restore_brain_agent_core_capability.sql');
const heartbeatConflictRepairSql=read('supabase/migrations/202607240005_fix_heartbeat_capability_conflict_ambiguity.sql');
const security=read('lib/brain-agent/security.server.ts'); const runtime=read('agent/src/runtime.ts'); const storage=read('agent/src/storage.ts'); const cli=read('agent/src/cli.ts');

test('migration remains additive, transactional, forced-RLS and browser-secret closed',()=>{assert.match(sql,/^--[\s\S]*\bBEGIN;/);assert.match(sql,/COMMIT;\s*$/);for(const table of ['device_pairing_requests','device_agent_credentials','device_agent_audit','device_capability_catalog','device_gateway_capabilities','device_agent_rate_limits'])assert.match(sql,new RegExp(`CREATE TABLE public\\.${table}`));assert.equal((sql.match(/FORCE ROW LEVEL SECURITY/g)??[]).length,6);assert.doesNotMatch(sql,/GRANT SELECT[^;]+authenticated/);});

test('rate admission uses one concurrency-safe upsert and bounded probabilistic cleanup',()=>{const fn=sql.slice(sql.indexOf('CREATE FUNCTION public.admit_device_agent_request'),sql.lastIndexOf('REVOKE ALL ON FUNCTION'));assert.match(fn,/INSERT INTO public\.device_agent_rate_limits AS limits[\s\S]*ON CONFLICT\(scope,identifier_hash\) DO UPDATE/);assert.match(fn,/request_count=CASE WHEN limits\.window_resets_at<=v_now THEN 1 ELSE limits\.request_count\+1 END/);assert.match(fn,/RETURNING limits\.\* INTO v_row/);assert.doesNotMatch(fn,/SELECT \* INTO v_row[\s\S]*FOR UPDATE/);assert.match(fn,/substr\(p_identifier_hash,1,2\)='00'/);assert.match(fn,/LIMIT 100/);assert.match(fn,/v_row\.request_count<=p_limit/);});

test('rate admission semantics cover first, active, expired, boundary, rejection and key isolation',()=>{const admit=(state,key,now,limit,seconds)=>{const prior=state.get(key);const next=!prior||prior.reset<=now?{count:1,reset:now+seconds}:{count:prior.count+1,reset:prior.reset};state.set(key,next);return next.count<=limit;};const state=new Map();assert.equal(admit(state,'a',0,2,60),true);assert.equal(admit(state,'a',1,2,60),true);assert.equal(admit(state,'a',2,2,60),false);assert.equal(admit(state,'b',2,2,60),true);assert.equal(admit(state,'a',60,2,60),true);assert.equal(state.get('a').count,1);});

test('trusted edge identity uses only Vercel-overwritten x-forwarded-for and HMAC storage',()=>{assert.match(security,/process\.env\.VERCEL === '1'/);assert.match(security,/headers\.get\('x-forwarded-for'\)/);assert.doesNotMatch(security,/x-vercel-forwarded-for|x-real-ip/);assert.match(security,/value\.includes\(','\)/);assert.match(security,/isIP\(value\) === 0/);assert.match(security,/BRAIN_AGENT_ALLOW_DEVELOPMENT_RATE_ADDRESS === 'true'/);assert.match(security,/createHmac\('sha256'/);assert.doesNotMatch(sql,/ip_address|raw_ip|inet/);});

test('strict peppers decode exactly 32-byte hex and must differ',()=>{assert.match(security,/\^\[0-9a-fA-F\]\{64\}\$/);assert.match(security,/Buffer\.from\(tokenValue, 'hex'\)/);assert.match(security,/token\.length !== 32 \|\| rate\.length !== 32 \|\| token\.equals\(rate\)/);assert.doesNotMatch(security,/console\.|logger|process\.argv/);});

test('re-pair preparation is owner-only, atomic, revokes old authority and clears paired metadata',()=>{const fn=sql.slice(sql.indexOf('CREATE FUNCTION public.prepare_device_gateway_repair'),sql.indexOf('CREATE FUNCTION public.admit_device_agent_request'));assert.match(fn,/p\.id=auth\.uid\(\) AND p\.status='active'/);assert.match(fn,/role NOT IN \('owner','super_admin'\)/);assert.match(fn,/FOR UPDATE/);assert.match(fn,/UPDATE public\.device_agent_credentials SET revoked_at=/);assert.match(fn,/UPDATE public\.device_pairing_requests SET revoked_at=/);assert.match(fn,/status='unpaired',last_seen_at=NULL,paired_at=NULL/);assert.match(fn,/agent\.repair_prepared/);assert.match(read('app/api/devices/agents/repair/route.ts'),/prepare_device_gateway_repair/);assert.match(read('components/camera-manager/BrainAgentManager.tsx'),/Prepare for re-pairing/);});

test('stable public IDs are unique only while credentials are active',()=>{assert.doesNotMatch(sql,/public_agent_id uuid NOT NULL UNIQUE/);assert.match(sql,/device_agent_credentials_active_public_agent_unique[\s\S]*public_agent_id\) WHERE revoked_at IS NULL/);assert.match(sql,/device_agent_credentials_active_gateway_unique/);assert.match(sql,/WHERE c\.public_agent_id=p_public_agent_id AND c\.revoked_at IS NULL FOR UPDATE/);});

test('production origin is exact and localhost is explicitly gated',()=>{assert.equal(validateBrainCloudOrigin('https://www.hospibrain.com'),'https://www.hospibrain.com');for(const value of ['http://www.hospibrain.com','https://hospibrain.com','https://api.www.hospibrain.com','https://www.hospibrain.com.','https://www.hospibrain.com:444','https://user:pass@www.hospibrain.com','https://www.hospibrain.com/?x=1','https://www.hospibrain.com/#x','https://www.hospibrain.com.evil.test'])assert.throws(()=>validateBrainCloudOrigin(value,false),/BRAIN_CLOUD_ORIGIN_NOT_ALLOWED/);assert.throws(()=>validateBrainCloudOrigin('http://localhost:3000',false));assert.equal(validateBrainCloudOrigin('http://localhost:3000',true),'http://localhost:3000');assert.throws(()=>validateBrainCloudOrigin('http://localhost:9999',true));});

test('pairing reuses only valid stored public agent UUIDs',()=>{const valid='A34E57F6-5669-4C09-9A2A-6244EC2CE8D4';assert.equal(resolvePublicAgentId(valid),valid.toLowerCase());for(const invalid of [undefined,'','acl-verification-only','00000000-0000-0000-0000-000000000000']){const generated=resolvePublicAgentId(invalid);assert.match(generated,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);assert.notEqual(generated,invalid);}});

test('every credential-bearing fetch rejects redirects',()=>{assert.equal((runtime.match(/redirect: 'error'/g)??[]).length,5);assert.doesNotMatch(runtime,/redirect:\s*'follow'/);for(const status of [301,302,307,308])assert.ok(status>=300&&status<400);});

test('only authenticated active credentials use agent identity while malformed and unknown credentials use trusted address',()=>{const route=read('app/api/agent/heartbeat/route.ts');assert.match(route,/resolve_device_agent_rate_identity/);assert.match(route,/p_credential_hash: parsed\.hash/);assert.match(route,/typeof activeCredentialId === 'string' \? agentHeartbeatRateKey\(activeCredentialId\) : requestAddressRateKey\(request\)/);assert.match(sql,/public_agent_id=p_public_agent_id AND c\.credential_hash=p_credential_hash AND c\.revoked_at IS NULL/);assert.match(security,/brain-agent-rate-v2:\$\{kind\}:\$\{value\}/);});

test('heartbeat distinguishes credential rejection from operational RPC failure',()=>{const route=read('app/api/agent/heartbeat/route.ts');assert.match(route,/X-Request-ID/);assert.match(route,/error\.message === 'AGENT_AUTHENTICATION_FAILED'/);assert.match(route,/authenticationFailure \? 401 : 503/);assert.match(route,/AGENT_HEARTBEAT_RPC_FAILED/);assert.match(route,/stage: 'authenticate_rpc'/);assert.match(route,/databaseCode: error\.code/);const diagnosticLog=route.slice(route.indexOf("console.warn('[Brain Agent Heartbeat]"),route.indexOf("console.warn('[Brain Agent Heartbeat]")+240);assert.doesNotMatch(diagnosticLog,/parsed|hash|authorization|credential/i);});

test('SQL capability validation is bounded, typed, formatted and declarations deduplicated',()=>{assert.match(sql,/CREATE FUNCTION private\.valid_agent_capability_declarations/);assert.match(sql,/jsonb_array_length\(p_value\) > 16 OR pg_column_size\(p_value\) > 2048/);assert.match(sql,/jsonb_typeof\(item\.value\) <> 'string'/);assert.match(sql,/\^\[a-z\]\[a-z0-9_\.\-\]\{2,79\}\$/);assert.equal((sql.match(/SELECT DISTINCT jsonb_array_elements_text/g)??[]).length,2);assert.equal(parseAgentMetadata({agentVersion:'1',platform:'win32',declaredCapabilities:['brain.heartbeat.v1','brain.heartbeat.v1']},false)?.declaredCapabilities.length,1);assert.equal(parseAgentMetadata({agentVersion:'1',platform:'win32',declaredCapabilities:['INVALID CAP']},false),null);});

test('unknown capability audit remains bounded without PL/pgSQL output-column ambiguity',()=>{assert.match(sql,/device_agent_audit_unknown_capability_bucket_unique/);assert.equal((auditRepairSql.match(/CREATE OR REPLACE FUNCTION public\.(?:consume_device_pairing_request|authenticate_device_agent_heartbeat)/g)??[]).length,2);assert.equal((auditRepairSql.match(/WHERE NOT EXISTS \(/g)??[]).length,2);assert.equal((auditRepairSql.match(/FROM public\.device_agent_audit AS audit/g)??[]).length,2);assert.equal((auditRepairSql.match(/audit\.gateway_id=v_gateway\.id/g)??[]).length,2);assert.equal((auditRepairSql.match(/v_event_bucket := date_trunc\('hour',clock_timestamp\(\)\)/g)??[]).length,2);assert.equal((auditRepairSql.match(/audit\.event_bucket=v_event_bucket/g)??[]).length,2);assert.equal((auditRepairSql.match(/EXCEPTION WHEN unique_violation THEN/g)??[]).length,2);assert.doesNotMatch(auditRepairSql,/ON CONFLICT\s*\(\s*gateway_id/i);assert.match(auditRepairSql,/ON CONFLICT ON CONSTRAINT device_gateway_capabilities_pkey/);assert.equal((auditRepairSql.match(/UNKNOWN_CAPABILITIES_IGNORED/g)??[]).length,2);assert.doesNotMatch(auditRepairSql,/outcome_code[^\n]*v_cap|event_type[^\n]*v_cap/);});

test('pairing heartbeat capability and repair paths qualify collision-prone identifiers',()=>{assert.equal((identifierRepairSql.match(/CREATE OR REPLACE FUNCTION public\.(?:consume_device_pairing_request|authenticate_device_agent_heartbeat)/g)??[]).length,2);assert.match(identifierRepairSql,/UPDATE public\.device_gateway_capabilities AS capability_row[\s\S]*WHERE capability_row\.gateway_id=v_gateway\.id AND capability_row\.capability_code=v_cap/);assert.equal((identifierRepairSql.match(/FROM public\.device_agent_audit AS audit_row/g)??[]).length,2);assert.equal((identifierRepairSql.match(/audit_row\.gateway_id=v_gateway\.id/g)??[]).length,2);assert.match(identifierRepairSql,/FROM public\.device_agent_credentials AS credential_row[\s\S]*credential_row\.public_agent_id=p_public_agent_id/);assert.match(identifierRepairSql,/UPDATE public\.device_pairing_requests AS request_row[\s\S]*WHERE request_row\.id=v_request\.id/);assert.match(identifierRepairSql,/UPDATE public\.device_agent_credentials AS credential_row[\s\S]*WHERE credential_row\.id=v_credential\.id/);assert.equal((identifierRepairSql.match(/UPDATE public\.device_gateways AS gateway_row/g)??[]).length,2);assert.doesNotMatch(identifierRepairSql,/WHERE\s+(?:gateway_id|company_id|location_id|capability_code|public_agent_id|credential_id|id)\s*=/i);const smoke=read('phase2a-smoke.sql');assert.match(smoke,/consume_device_pairing_request/);assert.match(smoke,/authenticate_device_agent_heartbeat/);assert.match(smoke,/unknown\.preview/);assert.match(smoke,/prepare_device_gateway_repair/);assert.match(identifierRepairSql,/REVOKE ALL ON FUNCTION[\s\S]*FROM PUBLIC, anon, authenticated, service_role;[\s\S]*GRANT EXECUTE ON FUNCTION[\s\S]*TO service_role;/);});

test('DPAPI and ACL handling are fixed-process, stdin-only and ACL-before-write fail closed',()=>{assert.match(storage,/spawnSync\(program, args, \{ input, encoding: 'utf8', shell: false/);assert.match(storage,/mkdir\(directory[\s\S]*hardenAcl\(directory, true\)[\s\S]*writeFile\(statePath[\s\S]*hardenAcl\(statePath, false\)/);assert.match(storage,/catch \(error\) \{ await rm\(statePath, \{ force: true \}\); throw error; \}/);assert.match(storage,/ConvertFrom-Json/);assert.match(storage,/JSON\.stringify\(\{ target, container \}\)/);assert.match(storage,/WindowsIdentity\]::GetCurrent\(\)\.User/);assert.doesNotMatch(storage,/process\.env\.USERNAME/);assert.match(storage,/SetAccessRuleProtection\(\$true,\$false\)/);assert.match(storage,/\$rules\.Count -ne 1/);assert.match(storage,/\$actual\.AreAccessRulesProtected/);assert.match(storage,/\$actualOwnerSid -ne \$expectedSid/);assert.match(storage,/\$ruleSid -ne \$expectedSid/);assert.match(storage,/\$rules\[0\]\.IsInherited/);assert.doesNotMatch(storage,/IdentityReference\.Value -ne \$identity\.Value/);assert.doesNotMatch(storage,/exec\(|shell: true/);});

test('pairing input is hidden and has no visible fallback',()=>{assert.match(cli,/input\.isTTY/);assert.match(cli,/input\.setRawMode\(true\)/);assert.match(cli,/HIDDEN_PAIRING_INPUT_REQUIRED/);assert.doesNotMatch(cli,/question\('One-time pairing code/);assert.doesNotMatch(cli,/console\.log\([^\n]*code/);});

test('pairing failures expose complete safe diagnostics without echoing credentials or pairing codes',()=>{const route=read('app/api/agent/pair/route.ts');assert.match(route,/X-Request-ID/);for(const reason of ['not_found','expired','already_used','gateway_mismatch','company_mismatch','validation_failure','authentication_failure'])assert.match(route,new RegExp(`'${reason}'`));for(const field of ['notFound','expired','alreadyUsed','gatewayMismatch','companyMismatch','validationFailure','authenticationFailure']){assert.match(route,new RegExp(field));assert.match(cli,new RegExp(field));}assert.match(cli,/Pairing API HTTP status/);assert.match(cli,/Pairing API safe error code/);assert.match(cli,/Pairing API request correlation ID/);assert.match(cli,/Pairing API full response/);assert.doesNotMatch(route,/pairingCode[^\\n]*(?:console|warn|log)/i);assert.doesNotMatch(cli,/Pairing API full response:[^\\n]*credential/i);});

test('pairing stage instrumentation logs only request identity and allowlisted internal codes',()=>{const route=read('app/api/agent/pair/route.ts');assert.match(route,/console\.warn\('\[Brain Agent Pairing\] Request rejected', \{ stage, requestId, internalErrorCode \}\)/);for(const code of ['PAIRING_SERVER_CONFIGURATION_MISSING','PAIRING_SECURITY_CONFIGURATION_MISSING','PAIRING_SECURITY_CONFIGURATION_INVALID','PAIRING_TRUSTED_CLIENT_ADDRESS_UNAVAILABLE','PAIRING_RATE_LIMIT_UNAVAILABLE','PAIRING_RATE_LIMIT_REJECTED','PAIRING_REQUEST_VALIDATION_FAILED','PAIRING_CREDENTIAL_GENERATION_FAILED','PAIRING_CONSUME_RPC_FAILED','PAIRING_CONSUME_RPC_EMPTY','PAIRING_FAILURE_DIAGNOSIS_FAILED','PAIRING_UNCLASSIFIED_FAILURE'])assert.match(route,new RegExp(`'${code}'`));const logHelper=route.slice(route.indexOf('function logPairingFailure'),route.indexOf('function pairingFailureResponse'));for(const forbidden of ['credential','pairingCode','codeHash','pepper','token','company','location','gateway','tenant','metadata','body','headers','error.code','error.message'])assert.doesNotMatch(logHelper,new RegExp(forbidden,'i'));assert.match(route,/message === 'BRAIN_AGENT_SECURITY_CONFIGURATION_MISSING'/);assert.match(route,/stage = 'rate_identity';[\s\S]*requestAddressRateKey\(request\)/);assert.match(route,/stage = 'credential_generation';[\s\S]*createAgentCredential/);});

test('fresh baselines restore the required core heartbeat capability reference',()=>{assert.match(coreCapabilitySql,/^--[\s\S]*\bBEGIN;/);assert.match(coreCapabilitySql,/COMMIT;\s*$/);assert.match(coreCapabilitySql,/INSERT INTO public\.device_capability_catalog/);assert.match(coreCapabilitySql,/VALUES \('brain\.heartbeat\.v1', 1, 'core', true\)/);assert.match(coreCapabilitySql,/ON CONFLICT \(capability_code\) DO NOTHING/);assert.doesNotMatch(coreCapabilitySql,/GRANT|ALTER|CREATE|DROP|UPDATE|DELETE/);});

test('heartbeat capability upsert uses the named key constraint to avoid output-column ambiguity',()=>{assert.match(heartbeatConflictRepairSql,/^--[\s\S]*\bBEGIN;/);assert.match(heartbeatConflictRepairSql,/COMMIT;\s*$/);assert.match(heartbeatConflictRepairSql,/CREATE OR REPLACE FUNCTION public\.authenticate_device_agent_heartbeat/);assert.match(heartbeatConflictRepairSql,/ON CONFLICT ON CONSTRAINT device_gateway_capabilities_pkey DO UPDATE/);assert.doesNotMatch(heartbeatConflictRepairSql,/ON CONFLICT\s*\(\s*gateway_id\s*,\s*capability_code\s*\)/);assert.match(heartbeatConflictRepairSql,/SECURITY DEFINER/);assert.match(heartbeatConflictRepairSql,/SET search_path = ''/);assert.match(heartbeatConflictRepairSql,/GRANT EXECUTE ON FUNCTION public\.authenticate_device_agent_heartbeat[\s\S]*TO service_role/);});

test('management errors preserve safe 401, 403 and generic 503 mapping',()=>{const helper=read('lib/brain-agent/management-auth.server.ts');assert.match(helper,/UNAUTHENTICATED' \? 401/);assert.match(helper,/status === 403 \? 'AGENT_FORBIDDEN'/);for(const route of ['app/api/devices/agents/route.ts','app/api/devices/agents/pairing/route.ts','app/api/devices/agents/revoke/route.ts','app/api/devices/agents/repair/route.ts'])assert.match(read(route),/agentManagementActorFailure/);});

test('Preview header acceptance is gated, authenticated and never reflects a raw address',()=>{const route=read('app/api/agent/header-acceptance/route.ts');assert.match(security,/process\.env\.VERCEL_ENV !== 'preview'/);assert.match(security,/timingSafeEqual/);assert.match(security,/fingerprintPrefix:[\s\S]*\.slice\(0, 12\)/);assert.doesNotMatch(route,/x-forwarded-for|rawAddress|address:/);assert.match(route,/Cache-Control.*private, no-store/);});

test('Preview SQL package is standalone and migration copy is exact',()=>{assert.equal(read('apply-202607220016.sql'),sql);for(const file of ['phase2a-preflight.sql','phase2a-verify.sql','phase2a-smoke.sql','phase2a-concurrency.sql'])assert.ok(read(file).trim().length>100);assert.match(read('phase2a-smoke.sql'),/PHASE2A_ROLLBACK_MARKER/);assert.match(read('phase2a-concurrency-runner.mjs'),/Promise\.all/);});

test('pairing remains single-use and agent authority remains service-role only',()=>{assert.match(sql,/WHERE r\.code_hash=p_code_hash FOR UPDATE/);assert.match(sql,/device_pairing_requests_active_gateway_unique/);const grants=sql.slice(sql.lastIndexOf('REVOKE ALL ON FUNCTION'));assert.match(grants,/consume_device_pairing_request/);assert.doesNotMatch(grants,/consume_device_pairing_request[^;]+TO authenticated/);assert.match(sql,/v_credential\.revoked_at IS NOT NULL/);});

test('backoff remains bounded and the command transport capability is explicit',()=>{assert.equal(backoffDelay(0,()=>0),750);assert.equal(backoffDelay(0,()=>1),1250);assert.ok(backoffDelay(20,()=>1)<=75000);assert.deepEqual(CAPABILITIES,['brain.heartbeat.v1','brain.command.transport.v1']);const cloud=[read('app/api/agent/pair/route.ts'),read('app/api/agent/heartbeat/route.ts'),read('app/api/agent/commands/claim/route.ts'),read('app/api/agent/commands/complete/route.ts')].join('\n');assert.doesNotMatch(cloud,/192\.168\.|\bRTSP\b|\bONVIF\b|\bFFmpeg\b|remote shell|child_process/i);});
