'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Copy, Plus, RefreshCw, Shield, Trash2, X } from 'lucide-react';
import { useLocale } from '@/components/LocaleProvider';
import { StatusBadge, type StatusTone } from '@/components/ui/StatusBadge';
type Gateway = { id:string; location_id:string|null; name:string; status:string; last_seen_at:string|null; agent_version:string|null; platform:string|null; paired_at:string|null };
type Pairing = { gateway_id:string; expires_at:string }; type Capability = { gateway_id:string; capability_code:string; declared_version:number; approved:boolean; revoked_at:string|null }; type Location = { id:string; name:string };

function gatewayStatusTone(status:string):StatusTone {
  if(status==='online')return 'success';
  if(status==='offline'||status==='disabled')return 'offline';
  if(status==='error'||status==='failed')return 'failed';
  if(status==='pending')return 'pending';
  return 'info';
}

export function BrainAgentManager({ locationId }:{ locationId:string }) {
  const { messages, language } = useLocale(); const t = messages.agents;
  const [gateways,setGateways]=useState<Gateway[]>([]),[pairings,setPairings]=useState<Pairing[]>([]),[capabilities,setCapabilities]=useState<Capability[]>([]),[locations,setLocations]=useState<Location[]>([]);
  const [canManage,setCanManage]=useState(false),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false); const [error,setError]=useState<string|null>(null),[name,setName]=useState('Local Brain Agent'); const [code,setCode]=useState<{value:string;expiresAt:string}|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch('/api/devices/agents',{cache:'no-store',headers:{Accept:'application/json'}});const payload=await response.json();if(!response.ok)throw new Error();setGateways(payload.data.gateways??[]);setPairings(payload.data.pairings??[]);setCapabilities(payload.data.capabilities??[]);setLocations(payload.data.locations??[]);setCanManage(payload.data.canManage===true);}catch{setError(t.unavailable);}finally{setLoading(false);}},[t.unavailable]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const visible=useMemo(()=>locationId?gateways.filter(item=>item.location_id===locationId):gateways,[gateways,locationId]); const locationName=(id:string|null)=>locations.find(item=>item.id===id)?.name??'';
  async function createGateway(event:React.FormEvent){event.preventDefault();const target=locationId||locations[0]?.id;if(!target)return;const response=await fetch('/api/devices/agents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locationId:target,name})});if(!response.ok){setError(t.unavailable);return;}setCreating(false);await load();}
  async function pair(gatewayId:string){const response=await fetch('/api/devices/agents/pairing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gatewayId})});const payload=await response.json();if(!response.ok){setError(t.unavailable);return;}setCode({value:payload.data.pairingCode,expiresAt:payload.data.expiresAt});await load();}
  async function revokePairing(gatewayId:string){await fetch('/api/devices/agents/pairing',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({gatewayId})});await load();}
  async function revoke(gatewayId:string){if(!confirm(t.confirmRevoke))return;await fetch('/api/devices/agents/revoke',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gatewayId})});await load();}
  async function prepareRepair(gatewayId:string){const question=language==='ar'?'هل تريد إلغاء الاعتمادات السابقة والتحضير لإعادة الإقران الآمن؟':'Revoke prior credentials and prepare this agent for secure re-pairing?';if(!confirm(question))return;const response=await fetch('/api/devices/agents/repair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gatewayId})});if(!response.ok){setError(t.unavailable);return;}await load();}
  return <section dir={language==='ar'?'rtl':'ltr'} className="rounded-3xl border border-white/10 bg-slate-950/60 p-4 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{t.title}</h2><p className="mt-1 text-sm text-slate-400">{t.description}</p></div><div className="flex gap-2">{canManage&&<button onClick={()=>setCreating(true)} className="ui-button-primary flex min-h-11 items-center gap-2 rounded-xl px-4 font-semibold"><Plus className="h-4 w-4"/>{t.add}</button>}<button onClick={()=>void load()} className="ui-button-secondary h-11 w-11 rounded-xl" aria-label="Refresh"><RefreshCw className="mx-auto h-4 w-4"/></button></div></div>
    {error&&<p role="alert" className="ui-alert ui-alert-error mt-4 rounded-xl p-3">{error}</p>}{loading?<p className="mt-6 text-slate-400">{t.loading}</p>:visible.length===0?<p className="mt-6 rounded-2xl border border-dashed border-white/15 p-6 text-center text-slate-400">{t.noAgents}</p>:<div className="mt-5 grid gap-3 md:grid-cols-2">{visible.map(item=>{const pairing=pairings.find(value=>value.gateway_id===item.id);return <article key={item.id} className="rounded-2xl border border-white/10 p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{item.name}</h3><p className="text-sm text-slate-400">{locationName(item.location_id)}</p></div><StatusBadge tone={gatewayStatusTone(item.status)} label={t.status[item.status as keyof typeof t.status]??item.status}/></div><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><dt className="text-slate-500">{t.lastSeen}</dt><dd>{item.last_seen_at?new Intl.DateTimeFormat(language,{dateStyle:'short',timeStyle:'short'}).format(new Date(item.last_seen_at)):t.never}</dd><dt className="text-slate-500">{t.version}</dt><dd>{item.agent_version??'—'}</dd><dt className="text-slate-500">{t.platform}</dt><dd>{item.platform??'—'}</dd></dl>{capabilities.filter(value=>value.gateway_id===item.id&&value.approved&&!value.revoked_at).map(capability=><p key={capability.capability_code} className="mt-2 text-xs text-cyan-200"><Shield className="me-1 inline h-3 w-3"/>{t.capability}: {capability.capability_code}</p>)}{canManage&&<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void pair(item.id)} className="ui-button-secondary min-h-11 rounded-xl px-3">{pairing?t.regenerate:t.pair}</button>{pairing&&<button onClick={()=>void revokePairing(item.id)} className="ui-button-secondary min-h-11 rounded-xl px-3">{t.revokePairing}</button>}{item.paired_at&&<button onClick={()=>void revoke(item.id)} className="ui-button-destructive min-h-11 rounded-xl px-3"><Trash2 className="me-1 inline h-4 w-4"/>{t.revokeAgent}</button>}{(item.status==='disabled'||item.paired_at)&&<button onClick={()=>void prepareRepair(item.id)} className="ui-button-secondary min-h-11 rounded-xl px-3">{language==='ar'?'التحضير لإعادة الإقران':'Prepare for re-pairing'}</button>}</div>}{pairing&&<p className="ui-alert ui-alert-warning mt-2 rounded-xl p-2 text-xs">{t.expires}: {new Intl.DateTimeFormat(language,{dateStyle:'short',timeStyle:'short'}).format(new Date(pairing.expires_at))}</p>}</article>})}</div>}
    {code&&<div role="dialog" aria-modal="true" className="ui-overlay fixed inset-0 z-50 flex items-end justify-center p-3 sm:items-center"><div className="ui-management-surface w-full max-w-lg rounded-3xl border p-5"><div className="flex justify-between"><h3 className="font-bold">{t.pair}</h3><button onClick={()=>setCode(null)} className="ui-button-secondary min-h-11 min-w-11 p-0"><X className="mx-auto"/></button></div><p className="ui-alert ui-alert-warning mt-3 rounded-xl p-3">{t.codeOnce}</p><code className="mt-4 block break-all rounded-xl bg-black p-4 text-lg text-white">{code.value}</code><button onClick={()=>void navigator.clipboard.writeText(code.value)} className="ui-button-primary mt-4 min-h-11 rounded-xl px-4"><Copy className="me-2 inline h-4 w-4"/>{t.copied}</button></div></div>}
    {creating&&<div role="dialog" aria-modal="true" className="ui-overlay fixed inset-0 z-50 flex items-end justify-center p-3 sm:items-center"><form onSubmit={createGateway} className="ui-management-surface w-full max-w-md rounded-3xl border p-5"><label className="font-semibold">{t.gatewayName}<input value={name} onChange={event=>setName(event.target.value)} className="ui-field mt-2 min-h-11 w-full rounded-xl px-3"/></label><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setCreating(false)} className="ui-button-secondary min-h-11 rounded-xl px-4">{t.cancel}</button><button className="ui-button-primary min-h-11 rounded-xl px-4">{t.create}</button></div></form></div>}
  </section>;
}
